Revert "UBUNTU: SAUCE: Fix intermittent OOB link up issue"
This reverts commit 50f0df71fab47c7e538203e7df1d183e71e6a8cc because it
breaks the build:

/tmp/kernel-smb-551965e-AFOM/build/drivers/net/ethernet/mellanox/mlxbf_gige/mlxbf_gige_main.c: In function 'mlxbf_gige_open':
/tmp/kernel-smb-551965e-AFOM/build/drivers/net/ethernet/mellanox/mlxbf_gige/mlxbf_gige_main.c:903:2: error: implicit declaration of function 'mlxbf_gige_mdio_enable_phy_int'; did you mean 'mlxbf_gige_mdio_handle_phy_interrupt'? [-Werror=implicit-function-declaration]
  903 |  mlxbf_gige_mdio_enable_phy_int(priv);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |  mlxbf_gige_mdio_handle_phy_interrupt

Signed-off-by: Stefan Bader <stefan.bader@canonical.com>