kbuild: add xilinx-sdirxss.h/xilinx-hls.h/xilinx-v4l2-events.h to no-header-test
When enabling CONFIG_UAPI_HEADER_TEST, there will be compile error as
below:

In file included from ./usr/include/linux/xilinx-sdirxss.h:7,
                 from <command-line>:32:
./usr/include/linux/videodev2.h:2418:20: error: field ‘timestamp’ has incomplete type
 2418 |  struct timespecx  timestamp;
      |                    ^~~~~~~~~

This is because that xilinx-sdirxss.h/xilinx-hls.h/xilinx-v4l2-events.h
include "videodev2.h" which includes "sys/timer.h". Just as what said in
commit d6fc9fcbaa655 ("kbuild: compile-test exported headers to ensure
they are self-contained"), these headers will result header-test failure
for some compilers. So let's add these 3 header to no-header-test list
just like other headers which include "videodev2.h"

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
State: pending
Signed-off-by: Hsuan-Yu Lin <shane.lin@canonical.com>