misc: xilinx-ai-engine: remove duplicate module init/exit
module_platform_driver() simply translates into module_init() and
module_exit(), hence conflicts as in below snippet. Fix it by moving
platform driver registration into existing module init/exit.

In file included from drivers/misc/xilinx-ai-engine/ai-engine-dev.c:17:
./include/linux/module.h:128:42: error: redefinition of '__inittest'
  128 |  static inline initcall_t __maybe_unused __inittest(void)  \
      |                                          ^~~~~~~~~~
./include/linux/device.h:1903:1: note: in expansion of macro 'module_init'
 1903 | module_init(__driver##_init); \
      | ^~~~~~~~~~~
./include/linux/platform_device.h:238:2: note: in expansion of macro 'module_driver'
  238 |  module_driver(__platform_driver, platform_driver_register, \
      |  ^~~~~~~~~~~~~
drivers/misc/xilinx-ai-engine/ai-engine-dev.c:444:1: note: in expansion of macro 'module_platform_driver'
  444 | module_platform_driver(xilinx_ai_engine_driver);
      | ^~~~~~~~~~~~~~~~~~~~~~
./include/linux/module.h:128:42: note: previous definition of '__inittest' was here
  128 |  static inline initcall_t __maybe_unused __inittest(void)  \
      |                                          ^~~~~~~~~~
./include/linux/module.h:111:32: note: in expansion of macro 'module_init'
  111 | #define postcore_initcall(fn)  module_init(fn)
      |                                ^~~~~~~~~~~
drivers/misc/xilinx-ai-engine/ai-engine-dev.c:435:1: note: in expansion of macro 'postcore_initcall'
  435 | postcore_initcall(xilinx_ai_engine_init);
      | ^~~~~~~~~~~~~~~~~
./include/linux/module.h:130:6: error: redefinition of 'init_module'
...

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Tested-by: Wendy Liang <wendy.liang@xilinx.com>
State: pending
Signed-off-by: Hsuan-Yu Lin <shane.lin@canonical.com>
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>