overlays: Delete spi0-hw-cs
BugLink: https://bugs.launchpad.net/bugs/1894873

The spi0-hw-cs overlay is unnecessary (and actually harmful) with the
current kernels. Delete it, leaving a note in the README and a
deprecation message from the firmware:

    dterror: overlay 'spi0-hw-cs' is deprecated: no longer necessary

Signed-off-by: Phil Elwell <phil@raspberrypi.com>

(cherry picked from commit 57905943666757ba6e6a25aaa898d99e9845493d rpi-5.4.y)
Signed-off-by: Juerg Haefliger <juergh@canonical.com>
Signed-off-by: Khalid Elmously <khalid.elmously@canonical.com>