media: hdr-ctrls: Add a missing include
The header has data types that have to be included from
types.h.

>> include/media/hdr-ctrls.h:59:2: error: unknown type name '__u8'
      59 |  __u8 eotf;
         |  ^~~~
...

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Reviewed-by: Dylan Yip <dylan.yip@xilinx.com>
State: pending
Signed-off-by: Hsuan-Yu Lin <shane.lin@canonical.com>
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>