Revert "loongarch/cpu: Switch to arch_cpu_finalize_init()"
BugLink: https://bugs.launchpad.net/bugs/2032632

This reverts commit 08e86d42e2c916e362d124e3bc6c824eb1862498 which is
commit 9841c423164787feb8f1442f922b7d80a70c82f1 upstream.

As Gunter reports:
	Building loongarch:defconfig ... failed
	--------------
	Error log:
	<stdin>:569:2: warning: #warning syscall fstat not implemented [-Wcpp]
	arch/loongarch/kernel/setup.c: In function 'arch_cpu_finalize_init':
	arch/loongarch/kernel/setup.c:86:9: error: implicit declaration of function 'alternative_instructions'

	Actually introduced in v6.1.44 with commit 08e86d42e2c9 ("loongarch/cpu:
	Switch to arch_cpu_finalize_init()"). Alternative instruction support
	was only introduced for loongarch in v6.2 with commit 19e5eb15b00c
	("LoongArch: Add alternative runtime patching mechanism").

So revert it from 6.1.y.

Reported-by: Guenter Roeck <linux@roeck-us.net>
Link: https://lore.kernel.org/r/fcd7b764-9047-22ba-a040-41b6ff99959c@roeck-us.net
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: Daniel Sneddon <daniel.sneddon@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Timo Aaltonen <timo.aaltonen@canonical.com>