UBUNTU: SAUCE: fix undefined symbol of cc_init
BugLink: https://bugs.launchpad.net/bugs/2037126

This patch fixes the following error.

> arch/x86/kernel/cpu/mshyperv.c:349: undefined reference to `cc_init'

CONFIG_GUEST_HYPERVISOR compiles mshyperv.o that reference cc_init().
cc_init() requires CONFIG_ARCH_HAS_CC_PLATFORM.
"select ARCH_HAS_CC_PLATFORM" when CONFIG_GUEST_HYPERVISOR=y.

Fixes: cbb5c73599cf ("x86/coco: Add API to handle encryption mask")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>
(cherry picked from http://github.com/intel/kernel-downstream.git/v6.5-tdx commit 387be3782df47261c63354df676e99956c585b44)
Signed-off-by: Philip Cox <philip.cox@canonical.com>