drm/i2c: adv7511: add missing include to drm/drm_probe_helper.h
Otherwise, the compiler complains about not being able to find the
`drm_helper_hpd_irq_event` symbol:

```
drivers/gpu/drm/i2c/adv7511.c: In function 'adv7511_irq_process':
drivers/gpu/drm/i2c/adv7511.c:450:3: error: implicit declaration of function 'drm_helper_hpd_irq_event' [-Werror=implicit-function-declaration]
  450 |   drm_helper_hpd_irq_event(adv7511->encoder->dev);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Florian Klink <flokli@flokli.de>
Reviewed-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Hsuan-Yu Lin <shane.lin@canonical.com>
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>