UBUNTU: SAUCE: drm/panel: Fix compilation error
BugLink: https://bugs.launchpad.net/bugs/1960323

In file included from <BUILD_DIR>/drivers/gpu/drm/tidss/tidss_dispc.c:27:
<BUILD_DIR>/include/drm/drm_panel.h:176:36: error: field ‘orientation’ has incomplete type
  176 |         enum drm_panel_orientation orientation;
      |                                    ^~~~~~~~~~~

Fixes: edd56feefbe0 ("drm/panel: Add and initialise an orientation field to drm_panel")
Signed-off-by: Juerg Haefliger <juergh@canonical.com>